version: "3"
services:
  backend:
    build: ./backend
    container_name: api_backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/my-db"
      SERVER_PORT: 4000
      TZ: Asia/Bangkok
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: client_frontend
    volumes:
      - ./frontend:/app
    command: npm start
    ports:
      - "5173:5173"
    depends_on:
      - backend
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    environment:
      TZ: Asia/Bangkok
volumes:
  data:
